INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖK-SU NAKLİYAT VE TİCARET LİMİTED ŞİRKETİ', '4050015850');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKŞEN TAAHHÜT TİCARET NAKLİYAT LİMİTED ŞİRKETİ', '4050022349');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU SİGORTA ARACILIK HİZMETLERİ LİMİTED ŞİRKETİ', '4050035888');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU AMBALAJ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '4050037387');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSULAR YAPI MARKET TURİZM TİCARET ORMAN VE SU ÜRÜNLERİ İTHALAT İHRACAT LİMİTED ŞİRKETİ.', '4050040607');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU GIDA İNŞAAT MADEN ORMAN ÜRÜNLERİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '4050041005');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU GIDA İNŞAAT VE TURİZM SANAYİ TİCARET LİMİTED ŞİRKETİ', '4050043692');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKTANLAR İNŞ.DOĞALGTES.TAAH.SAN.VETİC.LTD.ŞTİ.', '4050087257');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU GIDA', '4050176637');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSOYLAR HAFRİYAT İNŞAAT TEKSTİL HAYVANCILIK GIDA OTOMOTİV SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '4050244968');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKTAN KLİMA ISITMA SOĞUTMA OTOMASYON İNŞAAT ELEKTİRİK İTHALAT VE İHRACAT SANAYİ TİCARET LİMİTED Şİ', '4050287089');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKŞEN MÜHENDİSLİK MÜŞAVİRLİK İNŞ. TAAH. LTD.ŞTİ.', '4050312325');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU KUYUMCULUK SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '4050323302');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSÜM-Fİ İNŞAAT TAAH.EMLAK TESKS.TİC.LTD.ŞTİ.', '4050335347');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU GÖRÜNTÜLEME REHABİLİTASYON TEMİZLİK ALTYAPI TEKNOLOJİLERİ İNŞAAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '4050335494');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKŞİN TEKSTİL TUR. GIDA. İNŞ. SAN. VE. TİC. LTD. ŞTİ..', '4050336278');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSUN SU ÜRÜNLERİ LOKANTACILIK HAYVANCILIK GIDA KİMYA İNŞAAT TEKSTİL SANAYİ VE TİCARET LTD.ŞTİ.', '4050336308');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSÜGÜR İNŞAAT MÜHENDİSLİK SANAYİ VE TİCARET ANONİM ŞİRKETİ', '4050339020');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSULU YATÇILIK TUR.VE SEY.OTO.VE GID.TİC.LTD.ŞTİ', '4050339392');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKTAŞ MÜHENDİSLİK ENERJİ ISI DOĞALGAZ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '4050341562');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSUN MEKANİK MÜHENDİSLİK İTH. İHR. SAN. VE TİC. A.Ş.', '4050341806');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU2 ENERJİ ÜRETİM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '4050341977');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKTAŞ AJANS MATBAACILIK TEKSTİL ÜRÜNLERİ TİCARET LİMİTED ŞİRKETİ', '4050342009');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('PARKGRUP İNŞAAT YATIRIMLARI A.S.', '4050343162');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU4 ENERJİ ÜRETİM SANAYİ VE TİCARET ANONİM ŞİRKETİ', '4050345349');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKTAŞOĞLU TURİZM İNŞAAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '4050346038');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKTAŞ MONTAJ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '4050346375');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU GLOBAL GAYRİMENKUL DANIŞMANLIK İNŞAAT ANONİM ŞİRKETİ', '4050346672');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKŞİN GRUP İNŞAAT EMLAK DANIŞMANLIĞI GIDA SANAYİ VE TİC.A.Ş', '4050537594');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKŞEN SOĞUTMA ISITMA İNŞAAT AKSESUAR SANAYİ DIŞ TİCARET LİMİTED ŞİRKETİ', '4050545788');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSOY TARIM TİCARET LİMİTED ŞİRKETİ', '4050650555');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU ALTYAPI EKİPMANLARI VE İNŞAAT LİMİTED ŞİRKETİ', '4050653688');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU MİA AĞIZ VE DİŞ SAĞLIĞI HİZMETLERİ ANONİM ŞİRKETİ', '4050663946');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU GRUP KİMYA SANAYİ DIŞ TİCARET ANONİM ŞİRKETİ', '4050674991');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU KURUYEMİŞ GIDA PAZARLAMA SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '4050700243');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU ELEKTROMARKET BİLGİSAYAR TEKNOLOJİK BEYAZ EŞYA LOJİSTİK KAFETERYA İTH.İHR.VE SAN.TİC. LTD. ŞTİ', '4050709250');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU FIRIN İŞLETMECİLİĞİ LTD.ŞTİ.', '4050731283');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU ALÜMİNYUM İNŞAAT İÇ VE DIŞ TİCARET SANAYİ LİMİTED ŞİRKETİ', '4050755467');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSOY GROUP KİMYA ANONİM ŞİRKETİ', '4050756580');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSUR OTOMOTİV TARIM NAKLİYE İNŞAAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '4050764666');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('RE-PIE PORTFÖY YÖNETİMİ A.Ş. GÖKSU GAYRİMENKUL YATIRIM FONU', '4050766468');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSOY DİJİTAL İLETİŞİM TELEKOMÜNİKASYON PAZARLAMA LİMİTED ŞİRKETİ', '4050774708');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSUN ALÜMİNYUM TİCARET ANONİM ŞİRKETİ', '4050775580');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSUNLAR METAL GERİ DÖNÜŞÜM TİCARET LİMİTED ŞİRKETİ', '4050775709');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSUN FIRIN UNLU MAMÜLLERİ GIDA SAN.TİC.LTD.ŞTİ', '4050779020');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKŞEN ASTAR KUMAŞ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '4050779213');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKSU HAZIR GIDA TİCARET LİMİTED ŞİRKETİ', '4050780722');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('GÖKTAN GERİ DÖNÜŞÜM METAL TİCARET LİMİTED ŞİRKETİ', '4050782563');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('SS.KARAAĞAÇ TARIMSAL KALKINMA KOOPERATİFİ', '5050002871');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARABÜKLÜLER NAKLİYAT GIDA TURİZM SANAYİ VE TİCARET LİMİTED', '5050063113');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('SALİH YILMAZ BETON İNŞAAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '5050146691');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARABÜBER VİNÇ NAKLİYAT İNŞAAT PLATFORM TURİZM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5050489468');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARABÜK SEDEF KUYUMCULUK SAN. VE TİC. LTD. ŞTİ. - SEDEF ALTIN', '5050582486');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('SS. KARABÜK CUMAYANI KÖYÜ TARIMSAL KALKINMA KOOPERATİFİ', '5050583834');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACA TIBBİ BİTKİ ÜRÜNLERİ TARIM GAYRİMENKUL YATIRIM İNŞAAT SANAYİ LTD.ŞTİ.', '5050587958');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACALAR VİNÇ HAFRİYAT NAKLİYAT İNŞAAT HAYVANCILIK İTHALAT İHRACAT SANAYİ VE TİCARET LTD.ŞTİ.', '5050588730');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACAN AYDINLATMA ELEKTRİK İNŞAAT TAAHHÜT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5050589426');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACASPORT HALI İNŞAAT TEKSTİL SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5050590155');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACOĞLAN ELEKTRİK ÜRETİM İNŞAAT VE TEMİZLİK TAAHHÜT İŞLERİ SANAYİ TİCARET LİMİTED ŞİRKET', '5050590792');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACA OTOMAT GIDA İNŞAAT TURİZM TEKSTİL SANAYİ VE DIŞ TİCARET LİMİTED ŞİRKETİ', '5050591332');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACA GRUP ALÜMİNYUM METAL PASLANMAZ OTOMOTİV İNŞAAT MALZEMELERİ HIRDAVAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5050592534');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACAKAYA TARIM GIDA HAYVANCILIK ENERJİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5050593158');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARCANLAR TEKSTİL SANAYİ TİCARET LİMİTED ŞİRKETİ', '5050593254');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACAKAYA YAPI İNŞAAT ANONİM ŞİRKETİ', '5050594214');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACALAR DAYANIKLI TÜKETİM MALLARI SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5050594247');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACAOĞLAN ÖZEL EĞİTİM YAY. VE DAN.TİC.LTD.ŞTİ.', '5050594350');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('İNTEGRAL YOL YAPI İNŞAAT TAAHHÜT MİMARLIK ELEKTRİK PETROL DOĞALGAZ SANAYİ TİCARET ANONİM ŞİRKETİ', '5050594502');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACA MÜC. KUYUM. İNŞ. TAAH. GID. TİC. LTD. ŞTİ.', '5050594886');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACA İPEK İNŞAAT TURİZM NAKLİYE SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5050595617');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACA HOME TEKSTİL ÜRETİM A.Ş', '5050596073');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACA KONSTRÜKSİYON ÇELİK İNŞAAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5050596160');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARACA PEYZAJ İNŞAAT TEMİZLİK SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5050596650');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARABÜK KANYON İNŞAAT TAAHHÜT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5050830221');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('YAPITEK KONUT İNŞAAT TİCARET LİMİTED ŞİRKETİ', '5051161198');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARABÜRÇEK LİNYİT İŞLETMELERİ SAN. VE TİC. LTD. ŞTİ.', '5051171422');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('SINIRLI SORUMLU KARABÜK SAFRANBOLU OTO GALERİCİLER TOPLU İŞYERİ YAPI KOOPERATİFİ', '5051189334');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARABÜK BİRLİK MEDYA TİCARET LİMİTED ŞİRKETİ', '5051248364');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARABÜK KAHVEEVİ GIDA TURİZM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5051264484');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARABÜK COLOMBİA KAFE GIDA RESTORAN PASTANE TİCARET LİMİTED ŞİRKETİ', '5051304412');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARABÜK NET HABER BASIN TELEVİZYON İNTERNET YAYINCILIK VE TİCARET ANONİM ŞİRKETİ', '5051332151');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARABÜK SAKALLIOĞLU İNŞAAT MÜHENDİSLİK SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5051344122');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KARABÜK KÜTÜPHANE CAFE İŞLETMECİLİĞİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '5051348569');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜÇÜKSERİM SİGORTA ARACILIK HİZ.LTD.ŞTİ.', '6050008118');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜÇÜKSU UN VE UNLU MAM.SAN.TİC.LTD.ŞTİ.', '6050009918');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLEKÇİ TOPT TUH VE KONF TİC LTD ŞTİ', '6050042806');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLKEDİSİ MİMARLIK TAAHHÜT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050068812');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLTÜREL TURİZM EMLAK İNŞAAT TAAHHÜT OTOMOTİV İTHALAT İHRACAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050069136');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLÜNKOĞLU UNLU MAMÜLLERİ GIDA İNŞAAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050103254');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('TARİHİ YAYINLAR KÜLT. HİZM. KIRT. DAĞ. PAZ. SAN. VE TİC. LTD. ŞTİ.', '6050277272');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLCÜ PROJE İNŞAAT EMLAK ORMAN ÜRÜNLERİ TURİZM VE KOZMETİK TİCARET SANAYİ LİMİTED ŞİRKETİ', '6050291464');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜDÜR GİYİM-TEKSTİL- KOZMETİK- İLETİŞİM- ELEKTRİKLİ EV EŞYASI- SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050433423');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜÇÜKOVA İNŞAAT TURİZM MADENCİLİK GIDA AKARYAKIT OTOMOTİV TAŞIMACILIK SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050494927');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLTÜROĞLU ELEKTRİK MÜHENDİSLİK PROJE TAAHHÜT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050499701');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('SINIRLI SORUMLU KÜNAR TARIMSAL KALKINMA KOOPERATİFİ', '6050500527');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜME YEMEK HİZMETLERİ HAYVANCILIK TAŞIMACILIK ÖZEL GÜVENLİK HİZMETLERİ LTD. ŞTİ', '6050501528');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLÜNKOĞLU FIRINCILIK GIDA VE UNLU MAMÜLLERİ İNŞAAT TURİZM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050501712');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLT REKLAMCILIK ORG.HİZM.LTD.ŞTİ.', '6050501878');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜNCÜ UNLU MAMÜLLER GIDA TURİZM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050505040');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('SINIRLI SORUMLU KÜÇÜKSU KÖYÜ TARIMSAL KALKINMA KOOPERATİFİ', '6050505145');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜÇÜKTEKİN PETROL ÖZEL EĞİTİM TARIM VE CANLI HAYVAN TUR.İNŞ.SAN VE TİC.LTD.ŞTİ', '6050505522');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('BİRET MANAVGAT ET VE ET ÜRÜNLERİ TİCARET LİMİTED ŞİRKETİ', '6050509149');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜÇÜKSAAT GIDA TEMİZLİK ÜRÜNLERİ OTEL TURİZM LTD.ŞTİ.', '6050509702');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLCÜLER TURİZM EMLAK TAŞIMACILIK İNŞAAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050510798');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLAHÇI TEKSTİL İNŞAAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050511057');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('SINIRLI SORUMLU KÜÇÜKYONCALI TARIMSAL KALKINMA KOOPERATİFİ', '6050512677');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLTÜRPARK TENİS KULÜBÜ DERNEĞİ İKTİSADİ İŞLETMESİ', '6050514962');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜMBETLİ YAPI İNŞAAT A.Ş.', '6050519481');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜNCÜ PASTA ATÖLYESİ UNLU MAMÜLLER GIDA TURİZM İNŞAAT SANAYİ VE TİCARET ANONİM ŞİRKETİ', '6050520651');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLL GIDA LOKANTA İNŞAAT TURİZM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050765911');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜÇÜKYILDIZ OTOMOTİV MAKİNA TEKSTİL İNŞAAT GIDA TURİZM İTHALAT İHRACAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '6050767890');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLTÜRMOKKA TURİZM GIDA İHRACAT İTHALAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '6050811373');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLAHCIOĞLU İÇ MİMARLIK VE DAYANIKLI TÜKETİM MALLARI SANAYİ TİCARET LİMİTED ŞİRKETİ', '6050828348');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜÇÜKPARMAK ENERJİ YAPI SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050842952');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLT DANIŞMANLIK HİZMETLERİ ANONİM ŞİRKETİ', '6050867327');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLTE LOJİSTİK SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050874385');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜKS MOBİLYA METAL İNŞAAT GIDA SAN. VE TİC. LTD. ŞTİ.', '6050900697');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLTİGİN EĞİTİM KURUMLARI SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6050928543');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜN YAPI SANAYİ VE TİCARET ANONİM ŞİRKETİ', '6050953942');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('Kün Medya Yapım Anoni?m Şi?rketi?', '6050961012');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜFEMDE PAZARLAMA SPOR ALETLERİ GIDA MEDİKAL İTHALAT İHRACAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '6050977867');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLLİYAT EĞİTİM ÖĞRETİM TİCARET VE SANAYİ ANONİM ŞİRKETİ', '6051000135');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLSÜMZ OTELCİLİK TURİZM İHRACAT VE İTHALAT LİMİTED ŞİRKETİ', '6051013719');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLTÜR FIRIN UNLU MAMÜLLER SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6051025845');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLT TURİZM EĞLENCE ORGANİZASYON RESTORAN VE TİCARET LİMİTED ŞİRKETİ', '6051028442');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜHLER TURKEY İNŞAAT MAKİNA YEDEK PARÇA İMALAT VE İHRACAT İTHALAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '6051029250');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLÜNK GLOBAL DIŞ TİCARET ANONİM ŞİRKETİ', '6051030972');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLHANBEYİ İNŞAAT ELEKTRİK PETROL REKLAM TEKSTİL SANAYİ TİCARET  LİMİTED ŞİRKETİ', '6051034417');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜÇÜKPARK İLETİŞİM LİMİTED ŞİRKETİ', '6051037960');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜÇÜKYILDIZ PETROL SANAYİ VE TİC.LTD.ŞTİ.', '6051039540');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜF TAKI TASARIM LTD.ŞTİ.', '6051039654');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLTÜR TEKNİK SERVİS HİZMETLERİ SAN.VE DIŞ TİC.LTD.ŞTİ.', '6051050902');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLTÜR RESTORAN SAN. VE TİC. LTD. ŞTİ.', '6051051120');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLT SİNEMA ORGANİZASYON TURİZM İŞLETME SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6051052041');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜNÇ TATLILARI GIDA SANAYİ VE TİCARET LTD.ŞTİ.', '6051057117');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜFREVİ KUYUMCULUK İNŞAAT TAAHHÜT VE İNOVASYON TİCARET LİMİTED ŞİRKETİ', '6051060360');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLTAŞ KÜLTÜR TARIM ANONİM ŞİRKETİ', '6051063105');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLTÜR MÜHENDİSLİK MİMARLIK İNŞAAT GAYRİMENKUL PROJE GIDA SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '6051066270');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜÇÜKOSMAN LOJİSTİK İNŞAAT TURİZM VE TİCARET LİMİTED ŞİRKETİ', '6051073606');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLAHLI ZİRAAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '6051075005');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜLÇE KUYUMCULUK VE MÜCEVHER TİCARET LİMİTED ŞİRKETİ', '6051075456');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('KÜÇÜKSAN HIRDAVAT DEMİR ÇELİK SANAYİ TİCARET LİMİTED ŞİRKETİ', '6051082045');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSER BASKI MATBAACILIK VE AMBALAJ SANAYİ ANONİM ŞİRKETİ', '7050005165');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('SENTEZ OTOMOTİV SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050008511');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSİM İNŞAAT HAFRİYAT MADENCİLİK AKARYAKIT NAKLİYAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050010921');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZ SELAM ÇİNİ İMALAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050036989');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSAYAR PETROL İNŞAAT NAKLİYAT GIDA GAYRİMENKUL SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050040433');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY NAKLİYAT PETROL OTO TURİZM İNŞAAT ZİRAİ ÜRÜNLER HAYVANCILIK GIDA VE İHTİYAÇ MADDELERİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050042267');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('PROSEL YAPI VE BETON TEKNOLOJİLERİ SANAYİ TİCARET LTD ŞTİ', '7050044653');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSİM SİGORTACILIK ARACILIK  HİZMETLERİ LİMİTET ŞİRKETİ', '7050062068');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEL İNŞAAT NAKLİYAT TURİZM PETROL ÜRÜNLERİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050099974');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY İNŞAAT EMLAK SAĞLIK GIDA TEKSTSAN.VE TİC.LTD', '7050282787');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEL TEKNİK LTD.ŞTİ.', '7050287025');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEDA TEMİZLİK İNŞAAT EMLAK GIDA TURİZM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050292520');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY-HAN PROJE İNŞ TURİZM SAN TİC LTD ŞTİ', '7050294112');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEMT PLASTİK AMBALAJ TARIM ÜRÜNLERİ PAKETLEME NAKLİYAT İTHALAT İHRACAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050295113');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ALİ ÖZSOBACI ORT.', '7050295451');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEÇ PETROL SANAYİVE TİCARET ANONİM ŞİRKETİ', '7050296906');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('TEKRA MEDIKAL TEKNIK ELEKTRONIK SANAYI VE TICARET LIMITED SIRKETI', '7050298132');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSER ENDÜSTRİYEL MUTFAK EKİPMANLARI SERVİS SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050298238');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSERA GIDA PAZARLAMA TEMİZLİK İNŞAAT İTHALAT İHRACAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050298835');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY GLOBAL LOJİSTİK ANONİM ŞİRKETİ', '7050299045');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSERVET YAPI DEKORASYON İNŞ.MOB.OTO KİR.SAN.VE TİC.LTD.ŞTİ.', '7050299430');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY PARKE İNŞAAT EMLAK HAYVANCILIK NAKLİYE SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050300858');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSER GAYRİMENKUL İNŞAAT TURİZM GIDA SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050301286');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSERVET G.MENKUL İNŞ.KUYUM.TUR.TEKS.KONF.GID.A.Ş', '7050301316');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEV İNŞAAT TURİZM SAN.TİC.LTD.ŞTİ.', '7050301453');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSERABEY TARIM ÜRÜNLERİ İNŞAAT NAKLİYE PETROL SANAYİ VE TİCARET ANONİM ŞİRKETİ', '7050301574');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY SEÇGİN ALÜMİNYUM METAL SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050301621');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSAY HOME TEKSTİL SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050302454');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSER RESTORASYON İNŞAAT TAAHHÜT MÜHENDİSLİK LİMİTED ŞİRKETİ', '7050427771');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('PEK DONDURULMUŞ GIDA SANAYİ VE TİCARET ANONİM ŞİRKETİ', '7050429709');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY KAĞIT VE AMBALAJ SANAYİ TİCARET LİMİTED ŞİRKETİ', '7050460813');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSELL İLETİŞİM ELEKTRİK ELEKTRONİK İNŞAAT OTOMOTİV EMLAK İTHALAT İHRACAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '7050472947');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSERT İNŞAAT EMLAK SANAYİ TİCARET LİMİTED ŞİRKETİ', '7050488507');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY GRUP GIDA OTOMOTİV SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050510977');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSAY 06 OTO OTOMOTİV TURİZM SANAYİ TİCARET LİMİTED ŞİRKETİ', '7050521035');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEYREK İNŞAAT TEMİZLİK TAAHHÜT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050521114');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEV TURİZM OTELCİLİK VE TİCARET LİMİTED ŞİRKETİ', '7050521130');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSERHAT LOJİSTİK İNŞAAT VE TİCARET LİMİTED ŞİRKETİ', '7050522834');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSAY GRUP TARIM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050526706');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY PREFABRİK YAPI SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050527369');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY LOJİSTİK NAKLİYAT OTOMOTİV SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050529911');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY SULAMA SİSTEMLERİ TİC.LTD.ŞTİ', '7050530525');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSER CAM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050530867');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('İG GROUP DANIŞMANLIK İÇ VE DIŞ TİCARET LİMİTED ŞİRKETİ', '7050548373');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSE ENERJİ VE SANAYİ LİMİTED ŞİRKETİ', '7050552427');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSER SU GIDA DAĞITIM PAZARLAMA SAN. VE TİC. LTD. ŞTİ.', '7050553766');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY SULTANAHMET OTEL TURİZM TİCARET ANONİM ŞİRKETİ', '7050560231');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEL UNLU MAMULLERİ İNŞAAT GIDA FIRIN MAKİNALARI SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050562707');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEVGİ SAĞLIK HİZMETLERİ LİMİTED ŞİRKETİ', '7050563033');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEL INOX TEKNIK MAKINA SAN. VE TIC. LTD.STI.', '7050565364');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSİPAHİOĞLU OTOMOTİV GAYRİMENKUL İNŞAAT LİMİTED ŞİRKETİ', '7050567199');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOLAR ENERJİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050567742');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY AMBALAJ SANAYİ VE TİCARET ANONİM ŞİRKETİ', '7050571678');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEL ELEKTRİK VE İNŞAAT LİMİTED ŞİRKETİ', '7050571979');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY DERMOKOZMETİK MEDİKAL SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050572444');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEL TARIM ÜRÜNLERİ LOJİSTİK İÇ VE DIŞ TİCARET LİMİTED ŞİRKETİ', '7050576770');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSAY ENERJİ KİMYA SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050578015');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY REKLAM VE MEDYA HİZMETLERİ TİCARET LİMİTED ŞİRKETİ', '7050578641');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSİN ÖZEL EĞİTİM KURUMLARI VE TİC.LTD.ŞTİ.', '7050580486');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSOY TAAHHÜT MÜHENDİSLİK SANAYİ TİCARET LTD.ŞTİ.', '7050581605');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEY TARIM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '7050583990');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÖZSEÇ BETON MADENCİLİK İNŞAAT SANAYİ TİCARET ANONİM ŞİRKETİ', '7050584327');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER KARDEŞLER DENİZCİLİK SAN.VE TİC.AŞ.', '8050045086');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER TORNA TESVİYE İNŞAAT MOBİLYA GIDA ELEKTRONİK SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '8050045876');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER İNŞAAT EMLAK TURİZM OTOMOTİV TOPTAN ALTIN VE MÜCEVHERAT ALIM SATIMI İÇ VE DIŞ TİCARET LİMİTED ŞİRKETİ', '8050047501');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER HALI MOBİLYA ELEKTRİKLİ EV ALETLERİ TİCARET LİMİTED ŞİRKETİ', '8050067328');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ZİYA UÇAR TARIM ÜRN.ÜZÜM.AL.SAT.BAĞ.İML.İNŞ.TURZ.İTH.İHR.LTD.', '8050341164');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER KAYA MAKİNA TEKNİK HIRDAVAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '8050341750');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER ASANSÖR MALZEMELERİ PAZARLAMA SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '8050344298');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER DİZEL SİSTEMLERİ MOTORLU TAŞITLAR OTOMOTİV YEDEK PARÇA İTHALAT İHRACAT TİCARET SANAYİ LTD.', '8050344585');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER MOTOR MÜHENDİSLİK SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '8050350045');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER SALGIN VE ALİ ŞAHİN ORTAKLIĞI', '8050503589');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER İLETİŞİM GIDA İNŞAAT TAAHHÜT NAKLİYAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '8050612408');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER LOJİSTİK PETROL ÜRÜNLERİ PAZARLAMA DAĞITIM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '8050628061');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER PARKE BOYA ORMAN ÜRÜNLERİ İNŞAAT GIDA TİCARET VE SANAYİ LİMİTED ŞİRKETİ', '8050633954');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER MATBAACILIK KUTU AMBALAJ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '8050649724');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENERLER SİGORTA EKSPERLİĞİ LİMİTED ŞİRKETİ', '8050656041');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER AYAKKABI SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '8050673597');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER HEDİYELİK EŞYA SANAYİ VE TİCARET ANONİM ŞİRKETİ', '8050680169');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('BAYRAKTAR KUYUMCULUK-ŞENER BAYRAKTAR HAVVA BAYRAKTAR ADİ ORTAKLIĞI', '8050682765');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER ELCİK VE KALIP TİCARET LİMİTED ŞİRKETİ', '8050686965');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ŞENER ŞENER TARIM ÜRÜNLERİ GIDA NAKLİYE TİCARET LİMİTED ŞİRKETİ', '8050696609');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇPINAR TUĞLA KİREMİT AKARYAKIT NAKLİYAT TURİZM OTELCİLİK GIDA İNŞAAT İMALAT TAAHHÜT PAZARLAMA SANAYİ VE TİCARET ANONİM ŞİRKETİ', '9050001122');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇSOM MOTORLU ARAÇLAR SANAYİ VE TİCARET ANONİM ŞİRKETİ', '9050001460');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYILDIZ DEMİRCİOĞLU İTHALAT İHRACAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050008830');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYILDIZ TOPRAK SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050009196');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇ YILDIZ MAKİNA SAN TİC LTD ŞTİ', '9050009200');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇSEL İNŞAAT TURİZM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050036576');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇPINAR GIDA TURİZM İNŞAAT TEKSTİL TEMİZLİK TAŞIMACILIK OTOM. TİCARET VE SANAYİ LİMİTED ŞİRKETİ', '9050041436');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇTEM PLAS PLASTİK TEMİZLİK GIDA MADDELERİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050042775');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇPINAR SİGORTA ARACILIK HİZMETLERİ LİMİTED ŞİRKETİ', '9050086374');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLGEN NAK.İNŞ.OTO.TRAFİK MÜŞ.VE PETROL ÜRN.SAN.TİC.LTD.ŞTİ.', '9050112138');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYILDIZ KUYUMCULUK KONFEKSİYON TELEKOM GIDA SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050178896');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLGER TAŞIMACILIK TURİZM EMLAK İNŞAAT OTOMOTİV SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050210558');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLGER RESTORAN BESİCGIDA İNŞ.TURZ.OTOM.NAK.SAN.VE T.LTD.ŞTİ.', '9050241259');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYOLGIDA TEM.YAKITHAZIR BETON İNŞ.SAN. TİC.LTD.ŞTİ', '9050276987');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇPINAR ÇELİK DEMİR DÖKÜM HAYVANCILIK OTOMOTİV SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050287147');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇTEPE INSAAT TAAHHÜT EMLAK MÜHENDISLIK NAKLIYE TURIZM SANAYI VE TICARET LIMITED SIRKETI', '9050297108');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('AREN LOJİSTİK NAKLİYAT GEMİ ACENTALIĞI TİCARET LİMİTED ŞİRKETİ', '9050297964');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇSEM GIDA HAYVANCILIK İNŞAAT TURİZM LTD. ŞTİ.', '9050300124');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇSA MAKİNA YEDEK PARÇA HIRDAVAT GIDA SANAYİ TİCARET LİMİTED ŞİRKETİ', '9050301045');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜDY AKADEMİ EĞ. LTD. ŞTİ.', '9050302319');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('BAĞLAR VİNÇ İNŞAAT HAFRİYAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '9050306276');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYOL TURİZM TİCARET LİMİTED ŞİRKETİ', '9050306548');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇSER HİDROLİK PNÖMATİK MAKİNA İTHALAT İHRACAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050306920');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLGEN GROUP HEDİYELİK EŞYA BUJİTERİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050307179');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇTEPE ENERJİ TARIM HAYVANCILIK İNŞAAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050307944');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYÜZALTMIŞ TURİZM VE TİCARET A.Ş.', '9050308620');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇPINAR KONTİNÜ ZEYTİNYAĞI FABRİKASI ZEYTİNCİLİK İTHALAT İHRACAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050309172');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇZER MADENCİLİK İNŞAAT TEKSTİL NAKLİYE SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050309180');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLGEN DEKORASYON İNŞAAT GIDA SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050310595');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLGEN EĞİTİM TURİZM VE OTELCİLİK TAŞIMACILIK YAYINCILIK REHBERLİK TİCARET LİMİTED ŞİRKETİ', '9050311099');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLEŞ MADENCİLİK GIDA İNŞAAT TAŞIMACILIK OTOMOTİV İTHALAT İHRACAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050311901');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜGEY İNŞAAT MÜHENDİSLİK OTOMOTİV TURİZM GIDA SANAYİ TİCARET LİMİTED ŞİRKETİ', '9050311935');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYÜZOTUZÜÇ KUAFÖR VE GÜZELLİK SALONU LİMİTED ŞİRKETİ', '9050470776');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYILDIZ KARDEŞLER MOBİLYA AKSESUAR İNŞAAT İTHALAT İHRACAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050476313');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('YILDIZ RASPA GEMİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050516919');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYÜZONİKİ KUNDURA DERİ AYAKKABICILIK SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050521710');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇÜNCÜ BOYA VE YAPI SANAYİ TİCARET ANONİM ŞİRKETİ', '9050529372');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇTUR TAŞIMA TURİZM LİMİTED ŞİRKETİ', '9050540625');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('SINIRLI SORUMLU ÜÇSARAY KÖYÜ TARIMSAL KALKINMA KOOPERATİFİ', '9050578292');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇTEKNİK MAKİNE İMALAT MÜHENDİSLİK İNŞAAT TAAHHÜT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050578848');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇPINAR TEKSTİL TİCARET LİMİTED ŞİRKETİ', '9050581535');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇRENK OTOMOTİV SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050589591');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLGENLER TARIM ÜRÜNLERİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050591377');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇÖZ EMLAK İNŞAAT SAN TİC LTD ŞTİ', '9050593642');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLEK İNŞAAT İTHALAT İHRACAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050595782');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇTEPE MOTORLU ARAÇLAR SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050600229');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('UKS STAMPING METAL TEKNİK KALIP SANAYİ VE TİCARET ANONİM ŞİRKETİ', '9050601710');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLGEN MÜTEAHHİTLİK İNŞAAT SANAYİ VE TİC. LTD.ŞTİ.', '9050601868');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇREİSLER TURİZM YAT İŞLETMECİLİĞİ TİCARET VE SANAYİ LİMİTED ŞİRKETİ', '9050616533');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLBAY SAĞLIK HİZMETLERİ TİCARET LİMİTED ŞİRKETİ', '9050622677');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('U B TAŞ.LOJ.PET.GIDA TAR.VE HAY.İNŞ.TAAH.OTO.VETERİNERLİK SAN.TİC.İTH.İHR.LTD.ŞTİ.', '9050623531');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜK KAYALAR TAŞIMACILIK TURİZM TİCARET LİMİTED ŞİRKETİ', '9050645022');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜGE TARIM İTHALAT İHRACAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '9050647031');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('SINIRLI SORUMLU 333 NOLU İZMİR BALIKESİR KARAYOLU YOLCU TAŞIMA KOOPERATİFİ', '9050649881');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇSAN TOHUMCULUK SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050652071');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYOL İNŞAAT SANAYİ TİCARET LİMİTED ŞİRKETİ', '9050654225');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYILDIZ PELET ORMAN ÜRÜNLERİ İMALAT TİCARET LİMİTED ŞİRKETİ', '9050654513');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇTEPE MİMARLIK İNŞAAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050655848');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇTEPELER MÜHENDİSLİK MİMARLIK İNŞAAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050659488');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLGENÖZAL İÇ VE DIŞ TİCARET LİMİTED ŞİRKETİ', '9050661699');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLGER İPLİK TEKSTİL SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050664722');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYOL HAZIR BETON SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050665627');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLGÜ DIŞ TİCARET LİMİTED ŞİRKETİ', '9050665936');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇPINAR SU TURİZM SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050666026');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇÖZ MAKİNE SANAYİ TİCARET LİMİTED ŞİRKETİ', '9050672217');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇTEK OTOMOTİV SANAYİ VE TİCARET ANONİM ŞİRKETİ', '9050673009');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇTEPE MOTORS OTOMOBİL TİCARET ANONİM ŞİRKETİ', '9050679159');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜKER MEDİKAL ÖZEL SAĞLIK HİZMETLERİ TİCARET LİMİTED ŞİRKETİ', '9050679175');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜLGER KARDEŞLER GIDA SANAYİ VE TİCARET LİMİTED ŞİRKETİ', '9050679829');
INSERT INTO test_table_1 (company_name, company_number) VALUES ('ÜÇYILDIZ İNOVASYON TİCARET VE SANAYİ LİMİTED ŞİRKETİ', '9050682890');
